### ISSUE TITLE
Req. 50 Discussion Question

### ISSUE THREAD

**Issue by jlivingood** [ietf-llc/IASA2-Retrospective#4]
Question during community review: are there any remaining gaps or issues related to the definition of roles, responsibilities, and accountability between contractors and volunteers? How should the process of prioritizing long-term technical work function or be improved?

**Comment by jlivingood** [comment]
From the document: 
> Comments: This remains a key focus for the LLC, as there continues to be technical debt that needs to be addressed, and the IETF wishes to move towards more modern software architecture, systems architecture, software development practices and user-centred design. The current short-term focus is migrating core services off of tools.ietf.org onto managed IETF servers with a mix of like-for-like services, switching to new services (such as from Trac to GitHub) and replacing existing services with enhanced functionality. Resourcing continues to be a limiting factor and the LLC has increased the use of existing contractors, cultivated new contractors, and employed a new Senior Software Development Engineer to address this limitation, thus providing more capacity to take on a greater volume of technical work.

> We also observed that tension arose in the process of working towards meeting this requirement, as the LLC attempted (as required) to better define roles, responsibilities, and accountability between contractors and volunteers - especially when an individual was simultaneously both a contractor and a volunteer in a specific context. This appears to have been resolved and as the technical platforms of the IETF evolve it appears that roles, responsibilities, and accountabilities are becoming more clear cut and easier to understand.

`Question during community review (Respond at https://github.com/ietf-llc/IASA2-Retrospective/issues/4): are there any remaining gaps or issues related to the definition of roles, responsibilities, and accountability between contractors and volunteers? How should the process of prioritizing long-term technical work function or be improved?`

**Comment by richsalz** [comment]
Tread carefully.  While it seems useful to have a broad line between volunteer, employee, etc., experience has shown that we sometimes lose good people that we would rather not. I don't have any concrete suggestions to put in public, and I think the parties are aware of things I might say in private anyway.  Just admitting that this is a fraught issue, and one we all need to navigate carefully could help a lot.

**Comment by jlivingood** [comment]
To be posted to admin-discuss
Requirement 50 [1]
Related to this requirement we opened a discussion item [2] that asked whether there were any remaining gaps or issues related to the definition of roles, responsibilities, and accountability between contractors and volunteers. We also asked if there were suggestions on further improve the process of prioritizing long-term technical work that supports IETF work processes.

ACTION: If you have any remaining feedback - please provide it.

Thanks!
Jason

[1] https://github.com/ietf-llc/IASA2-Retrospective/blob/main/draft-iasa2-retrospective.md
[2] https://github.com/ietf-llc/IASA2-Retrospective/issues/4

**Comment by jlivingood** [comment]
Close out Req 50 in latest update
