### ISSUE TITLE
Sponsorship figures

### ISSUE THREAD

**Issue by jlivingood** [ietf-llc/IASA2-Retrospective#43]
@JayDaley Can you please determine what the sponsorship $ was in EOY 2018 and EOY 2023 and add that in the requisite section (as well as % and $ change). Thx!

**Comment by jlivingood** [comment]
From Debbie:
From the internally posted 2018 financial statements, the Sponsorship revenue was $1,489,736.  For 2023, Sponsorship Revenue was $1,475,741

**Comment by jlivingood** [comment]
@JayDaley What else do you think we should say here? The numbers above would suggest we have lost ground, relative to inflation, on sponsorship funds.

**Comment by JayDaley** [comment]
We do have a downward trend due to companies dialling back, but it is more likely that the 2018 figures include some other donations that are counted differently in 2023.  I will check
