### ISSUE TITLE
Attendee Info

### ISSUE THREAD

**Issue by jlivingood** [ietf-llc/IASA2-Retrospective#51]
> At the same time, the employers of some IETF participants have sought to control or reduce travel-related expenses for meetings, and there are an increasing number of self-funded, grant-funded and not-for-profit-funded participants who have the same aim. 

Per Roman: How do we know this?  Specifically, that there is an increase.

**Comment by JayDaley** [comment]
From:
* Talking to people
* Increased concerns being raised about costs
* Increased number of onsite fee waiver requests
