### ISSUE TITLE
Meeting Cost Discussion

### ISSUE THREAD

**Issue by jlivingood** [ietf-llc/IASA2-Retrospective#52]
> This has prompted a range of questions about the IETF's approach to meetings, including the cost of where we meet, how to maximize the benefits when we do meet, what form of funding support the IETF can provide to IETF participants, and whether the three meeting per year cadence remains the best operating model for the IETF. These issues must be addressed, if at all, by the IESG; the IETF LLC would then operationalize any change in approach to the conduct of meetings. The IESG may therefore wish to conduct a community assessment to determine whether any future changes are appropriate. 

Per Roman, "What is the IESG's role in this meeting property?"

JL: ISTM we note that the IESG leads on things like 3/yr vs 2/yr meetings and so on. What else do we want to raise or clarify here?

**Comment by rdanyliw** [comment]
Upon re-review, I agree with you. No action. I was initially reacting to the "cost of where we meet" as something the LLC does, not the IESG.  However, the other examples of meeting cadence are for the IESG to handle.
