### ISSUE TITLE
"Greater Care" issue

### ISSUE THREAD

**Issue by jlivingood** [ietf-llc/IASA2-Retrospective#56]
> With the growth of the internal team and the rapid progress in some areas, 
    greater care is now being taken to check with the community that the LLC is
    delivering the changes that the community has prioritized.

Per Roman, "How is this "greater care" being done now?"

@JayDaley Any suggestions on changes to the text?

**Comment by JayDaley** [comment]
The 'greater care' is in the Tools Team meetings where we have switched from asking for questions, to explicitly asking people to review development plans and provide feedback on priorities.

**Comment by jlivingood** [comment]
Can you propose additional text to clarify a bit?
