### ISSUE TITLE
RPC Text Discussion

### ISSUE THREAD

**Issue by jlivingood** [ietf-llc/IASA2-Retrospective#59]
> Another might be attributable to how the internal work processes of the RPC are quantitatively measured and incrementally improved over time. It is also notable that the changes introduced by [XMLv3](https://datatracker.ietf.org/doc/html/rfc7991) have not shown a meaningful improvement for RPC output. 

Per Roman, what does " and incrementally improved over time" mean?

>  It is also notable that the changes introduced by [XMLv3](https://datatracker.ietf.org/doc/html/rfc7991) have not shown a meaningful improvement for RPC output. 

Per Roman, "What was the basis for believing that using XMLv3 would improve RFC output?  What is meant by output?  Is the improvement in the document or the time it take to process the document?"

**Comment by JayDaley** [comment]
I didn't write the original text do I can't answer the questions, but I will suggest a rewrite of that text in a PR.
