### ISSUE TITLE
Managing Director Role - Comment from Brian Carpenter

### ISSUE THREAD

**Issue by jlivingood** [ietf-llc/IASA2-Retrospective#71]
> This would appear to obviate the need for a special Managing Director role.
>
> The IETF LLC proposes to address this with a new RFC that replaces references to the IETF Secretariat with the more generic term 'IASA' and removes any references to individual administrative support roles that do not require a nominated individual to deliver them.

I agree that the role is OBE and that an RFC to patch the language would be appropriate and non-controversial. But to be picky, you should write:

"The IETF LLC proposes to address this by requesting the IETF to publish a new RFC ..."

because the LLC cannot itself publish RFCs.

Regards
     Brian Carpenter

**Comment by Kmb1980** [comment]
Ye I'm working on. The original creator to get on board a few politics there but I'm going to deliver I should know by  tomorrow afternoon
