### ISSUE TITLE
Req. 34, Discussion Item 5

### ISSUE THREAD

**Issue by jlivingood** [ietf-llc/IASA2-Retrospective#9]
Question during community review: Should a goal for maintaining at least one independent Director be considered (regardless of whether that Director is appointed by the IETF NomCom, ISOC, or the LLC itself) or has the current structure worked well and permitted the appropriate flexibility in the selection process?

**Comment by jlivingood** [comment]
From the document:
> Discussion Area 2: The composition of the inaugural Board deliberately included Directors that brought independent experience and viewpoints. It has been the Board’s experience that this has added a valuable diversity of skills, experience, networks and perspectives, and is generally considered a board best practice (see related IASA2 list discussion, such as here). While having one or more independent Directors has been useful, it is not a formally defined requirement in the composition of the Board. At the same time, some members of the community have expressed a preference for fewer or no independent Directors, in favor of more or all Directors coming from directly within the IETF community. One path is to leave things as they are, which is to not specify that having one or more independent Directors is either useful or a specific goal, which allows for the greatest flexibility as circumstances and needs change over time. On the other hand, it seems possible that a case could be made that having at least one independent Director is a best practice and should be defined as a goal of Board composition in some manner.

`Question during community review (Respond at https://github.com/ietf-llc/IASA2-Retrospective/issues/9): Should a goal for maintaining at least one independent Director be considered (regardless of whether that Director is appointed by the IETF NomCom, ISOC, or the LLC itself) or has the current structure worked well and permitted the appropriate flexibility in the selection process?`

**Comment by richsalz** [comment]
I think it is worth *trying* to have an independent director, but would tie it in to the "more than five" situation.

**Comment by jlivingood** [comment]
Community feedback so far is that if independent directors are needed, or ones with specific experience, that the board could appoint those via the available process. Or, if there was a need to update the NomCom requirements then this could be done via the annual community review of LLC NomCom requirements at https://github.com/ietf-llc/NomCom-Requirements.
